[env]
_.path = ['./node_modules/.bin']

[tools]

bun = 'latest'
deno = 'latest'
node = 'lts'
"npm:@fission-ai/openspec" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:repomix" = "latest"

go = 'latest'

python = '3.14.5'

java = 'temurin-25.0.3+9.0.LTS'
maven = 'latest'

rust = { version = "latest" }
"cargo:tauri-cli" = 'latest'

fnox = "latest"

[plugins]

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
experimental = true
