name: Sync labels
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          exclude: |
            help*
            *issue
